### ISSUE TITLE
Issue: Installing pipenv for the new user

### ISSUE THREAD

**Issue by jogoldbach** [flathunters/flathunter#496]
**When running:**
`sudo -u flathunter /home/flathunter/.local/bin/pipenv install`

**I get the following:**
_sudo: /home/flathunter/.local/bin/pipenv: command not found_

All the previous steps have worked for me (Installation with Linux).

Does anyone have any idea what I might be doing wrong?

Thanks in advance :)

**Comment by Beast-Sanjay** [comment]
@jogoldbach The error message you're encountering, "sudo: /home/flathunter/.local/bin/pipenv: command not found," suggests that the `pipenv` command is not in the `sudo` user's `PATH`. To resolve this issue, you can take the following steps:

1.Check `pipenv` Installation Path:
   Verify that `pipenv` is installed in `/home/flathunter/.local/bin`. If it's not there, you should ensure it's correctly installed.

2. Ensure `pipenv` is Installed:
   Confirm that `pipenv` is installed in your user's environment. You can check this by running `pipenv --version` without `sudo`. If it returns the version, it means `pipenv` is installed for your user.

3. Check `sudo` User's `PATH`:
   The error indicates that the `pipenv` command is not found for the `sudo` user. This is likely due to differences in the `PATH` environment variable for regular users and the `sudo` user.

   To resolve this, you can try running `pipenv` with the full path:

   ```bash
   sudo -u flathunter /home/flathunter/.local/bin/pipenv install
   ```

   This specifies the full path to the `pipenv` executable. If `pipenv` is correctly installed in that location, it should work.

4. Add `pipenv` to the `sudo` User's `PATH`:
   If you want the `pipenv` command to be available to the `sudo` user without specifying the full path every time, you can modify the `sudo` user's `PATH` environment variable to include the directory where `pipenv` is installed.

   Edit the `sudo` user's `~/.bashrc` or `~/.bash_profile` or any other relevant shell configuration file. Add the following line to append the `pipenv` directory to the `PATH`:

   ```bash
   export PATH="/home/flathunter/.local/bin:$PATH"
   ```

   Save the file, and the next time you use `sudo`, it should have access to the `pipenv` command without specifying the full path.

Remember to use caution when modifying the `PATH` for the `sudo` user, as it can affect system security. Only modify the `sudo` user's `PATH` if you are confident that it's safe to do so.

Hope this finds your solution.

**Comment by jogoldbach** [comment]
@Beast-Sanjay Thank you very much. It was weirdly in the wrong directory. I uninstalled and installed `pipenv` again normally.

:)
